apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythondemoapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pythondemoapp
  template:
    metadata:
      labels:
        app: pythondemoapp
    spec:
      containers:
      - name: pythondemoapp
        image: asia-south1-docker.pkg.dev/excellent-guide-410011/anil-cicd-demo-dev-repo/pythondemoimage@sha256:a3266394387e4ede5a9863cf74cbdfaebcb09dc95c31f105ae221d43caa2d9f5
        ports:
        - containerPort: 9090
